//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_angular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientHistory
    {
        public int Id { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public string Smoking { get; set; }
        public string Alcohol { get; set; }
        public string DrugUsage { get; set; }
        public string Surgeries { get; set; }
        public int PatientHistoryId { get; set; }
    }
}
